spring:
  datasource:
    url: jdbc:h2:mem:nee;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    password: Password123!
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2