server:
  port: 8088
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  tomcat:
    threads:
      worker: 64
      io: 4

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=nee;trustServerCertificate=true
    username: SA
    password: Password123!
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      minimum-idle: 10
      pool-name: master

jpa:
  open-in-view: false
  show-sql: true
  hibernate:
    ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties:
    "[hibernate.dialect]": org.hibernate.dialect.SQLServer2012Dialect
    "[hibernate.generate_statistics]": false
    "[hibernate.connection.provider_disables_autocommit]": true